[package]
name = "tabled_color"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tabled = { git = "https://github.com/zhiburt/tabled/", branch = "try-improve-perf-of-printing", features = ["color"] }
